### ISSUE TITLE
How to edit pbdb.jet file?

### ISSUE THREAD

**Issue by lovebdsobuj** [arashpayan/Prayer-Book-Android#18]
How to edit .[pbdb.jet](https://github.com/arashpayan/Prayer-Book-Android/tree/master/app/src/main/assets) file?

**Comment by arashpayan** [comment]
It's not meant to be manually edited. I use https://github.com/arashpayan/pbdbbuilder to create database files for individual languages, and more recently https://github.com/arashpayan/bpnet-scraper for getting languages directly from the bahaiprayers.net API. Then I merge the individual db's into a single file (pbdb.jet) using `bpnet-scraper`.
