### ISSUE TITLE
pbdb.jet

### ISSUE THREAD

**Issue by amirrezasamandi** [arashpayan/Prayer-Book-Android#19]
i try to edit your application (android prayer book) but i cant edit and view pdbd.jet in assect folder on res,please say to me than what am i do than edit ,jet file

**Comment by arashpayan** [comment]
The pbdb.jet file is just an sqlite file. It's not designed to be edited by hand. The latest version of the database was generated by my bpnet-scraper utility (https://github.com/arashpayan/bpnet-scraper).
